BUSINESS_SECTORS = ["Agriculture", "Food & Beverage", "Fashion & Textile", "Beauty", "Healthcare", "Tourism", "Education", "Technology", "Manufacturing", "Creative Industry", "Trading", "Finance", "Professional Services", "Others"]
COUNTRIES = ["Malaysia", "China", "Indonesia", "Singapore", "Thailand", "Cambodia", "Vietnam", "Philippines", "Brunei", "Laos", "Myanmar", "Other"]
PARTICIPATION_CATEGORIES = ["Delegate", "Speaker", "Buyer", "Investor", "Government", "Association", "Media", "Exhibitor", "Sponsor", "Other"]
LOOKING_FOR = ["Buyer", "Distributor", "Importer", "Retailer", "Investor", "Technology Partner", "Joint Venture", "Government", "Others"]
PREFERRED_COUNTRIES = ["Indonesia", "Malaysia", "China", "Singapore", "Thailand", "Vietnam", "Cambodia", "Philippines", "Others"]
ROOM_PREFERENCES = ["Twin Sharing", "Single Room (+Supplement)"]
AIRPORTS = ["CGK", "HLP", "Other"]
BOOTH_SIZES = ["Standard Booth 3x3", "Premium Booth", "Custom Booth"]
